module.exports = {
	root: true,
	globals: {
		MyGlobal: true,
	},
	env: {
		browser: true,
		es2021: true,
		node: true,
	},
	extends: [
		'eslint:recommended',
		'plugin:react/recommended',
		'plugin:@typescript-eslint/eslint-recommended',
		'plugin:@typescript-eslint/recommended',
	],
	plugins: ['import', 'jsx-a11y', 'react', 'react-hooks'],
	rules: {
		semi: ['error', 'never'],
		quotes: ['error', 'single'],
		indent: ['error', 'tab'],
		curly: ['error', 'multi'],
		eqeqeq: ['error', 'smart'],
		'new-parens': 'error',
		'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
		'no-extra-bind': 'error',
		'no-floating-decimal': 'error',
		'no-multi-spaces': 'error',
		'array-bracket-spacing': ['error', 'never'],
		'implicit-arrow-linebreak': ['error', 'beside'],
		'computed-property-spacing': ['error', 'never'],
		'brace-style': ['error', 'stroustrup'],
		'space-infix-ops': 'error',
		'arrow-spacing': 'error',
		'no-const-assign': 'error',
		'no-var': 'error',
		'rest-spread-spacing': ['error', 'never'],
		'lines-around-comment': [
			'error',
			{
				beforeBlockComment: true,
				beforeLineComment: true,
				allowBlockStart: true,
				allowBlockEnd: true,
				allowClassStart: true,
				allowClassEnd: true,
				allowObjectStart: true,
				allowArrayStart: true,
			},
		],
		'padding-line-between-statements': [
			'error',
			{ blankLine: 'always', prev: '*', next: 'return' },
			{ blankLine: 'always', prev: '*', next: 'try' },
			{ blankLine: 'always', prev: '*', next: 'function' },
			{ blankLine: 'always', prev: '*', next: 'class' },
			{ blankLine: 'always', prev: '*', next: 'cjs-export' },
		],
		'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1 }],
		'lines-between-class-members': ['error', 'always'],
		'eol-last': ['error', 'always'],
		'comma-spacing': ['error', { before: false, after: true }],
		'block-spacing': 'error',
		'comma-style': ['error', 'last'],
		'jsx-quotes': ['error', 'prefer-single'],
		'key-spacing': ['error', { beforeColon: false }],
		'@typescript-eslint/no-empty-interface': 0,
		'@typescript-eslint/ban-types': [
			2,
			{
				types: {
					Function: {
						message: 'Prefer a specific function type, like `() => void`.',
					},
				},
			},
		],
		'no-use-before-define': 0,
		'@typescript-eslint/no-use-before-define': 2,
		'no-shadow': 0,
		'@typescript-eslint/no-shadow': 2,
		'no-console': 2,
		'linebreak-style': 0,
		'react/jsx-uses-react': 'off',
		'react/react-in-jsx-scope': 'off',
	},
	settings: {
		react: {
			version: 'detect',
		},
	},
	parser: '@typescript-eslint/parser',
	parserOptions: {
		sourceType: 'module',
		ecmaFeatures: { jsx: true },
	},
}
